"use client";

import { motion } from "motion/react";

// Aceternity UI — World Map, themed for TOGL.
// The dotted base map is pre-generated by scripts/generate-map.mjs into
// public/maps so the `dotted-map` geodata never ships to the browser.

type Point = { lat: number; lng: number; label?: string; labelSide?: "left" | "right" };

interface MapProps {
  dots?: Array<{ start: Point; end: Point }>;
}

// Keep in sync with `region` in scripts/generate-map.mjs
const MAP_REGION = { latMax: 77, latMin: -58 };
const VIEW_W = 800;
const VIEW_H = (VIEW_W * (MAP_REGION.latMax - MAP_REGION.latMin)) / 360;

const projectPoint = (lat: number, lng: number) => ({
  x: ((lng + 180) / 360) * VIEW_W,
  y: ((MAP_REGION.latMax - lat) / (MAP_REGION.latMax - MAP_REGION.latMin)) * VIEW_H,
});

const createCurvedPath = (
  start: { x: number; y: number },
  end: { x: number; y: number },
) => {
  const midX = (start.x + end.x) / 2;
  const distance = Math.hypot(end.x - start.x, end.y - start.y);
  const midY = Math.min(start.y, end.y) - Math.min(70, 16 + distance * 0.22);
  return `M ${start.x} ${start.y} Q ${midX} ${midY} ${end.x} ${end.y}`;
};

export default function WorldMap({ dots = [] }: MapProps) {
  const origin = dots[0]?.start;

  return (
    <div className="relative aspect-[800/300] w-full font-sans">
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src="/maps/world-dots.svg"
        className="pointer-events-none h-full w-full opacity-[0.28] select-none [mask-image:linear-gradient(to_bottom,transparent,white_8%,white_92%,transparent)]"
        alt=""
        width="800"
        height="300"
        loading="lazy"
        draggable={false}
      />
      <svg
        viewBox={`0 0 ${VIEW_W} ${VIEW_H}`}
        className="pointer-events-none absolute inset-0 h-full w-full overflow-visible select-none"
        role="img"
        aria-label={`Trade lanes from ${origin?.label ?? "Colombo"} to ${dots
          .map((d) => d.end.label)
          .join(", ")}`}
      >
        <defs>
          <linearGradient id="lane-gradient" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#a7d046" stopOpacity="0" />
            <stop offset="12%" stopColor="#00a558" />
            <stop offset="55%" stopColor="#1d6b91" />
            <stop offset="90%" stopColor="#2b519a" />
            <stop offset="100%" stopColor="#243f7a" stopOpacity="0" />
          </linearGradient>
        </defs>

        {dots.map((dot, i) => {
          const s = projectPoint(dot.start.lat, dot.start.lng);
          const e = projectPoint(dot.end.lat, dot.end.lng);
          const d = createCurvedPath(s, e);
          return (
            <g key={`lane-${i}`}>
              <motion.path
                d={d}
                fill="none"
                stroke="url(#lane-gradient)"
                strokeWidth="1.1"
                strokeLinecap="round"
                initial={{ pathLength: 0, opacity: 0 }}
                whileInView={{ pathLength: 1, opacity: 1 }}
                viewport={{ once: true, margin: "-10% 0px" }}
                transition={{ duration: 1.4, delay: 0.25 * i, ease: "easeOut" }}
              />
              {/* A small parcel travelling the lane */}
              <circle r="1.8" fill="#2b519a" className="motion-reduce:hidden">
                <animateMotion
                  dur={`${4 + (i % 3)}s`}
                  begin={`${1.4 + 0.25 * i}s`}
                  repeatCount="indefinite"
                  path={d}
                />
              </circle>
            </g>
          );
        })}

        {dots.map((dot, i) => {
          const e = projectPoint(dot.end.lat, dot.end.lng);
          const labelLeft = dot.end.labelSide === "left";
          return (
            <g key={`hub-${i}`}>
              <circle cx={e.x} cy={e.y} r="2.2" fill="#243f7a" />
              <circle cx={e.x} cy={e.y} r="2.2" fill="#243f7a" opacity="0.4">
                <animate attributeName="r" from="2" to="7" dur="2s" repeatCount="indefinite" />
                <animate attributeName="opacity" from="0.4" to="0" dur="2s" repeatCount="indefinite" />
              </circle>
              {dot.end.label && (
                <text
                  x={labelLeft ? e.x - 5 : e.x + 5}
                  y={e.y + 3}
                  textAnchor={labelLeft ? "end" : "start"}
                  className="fill-ink-muted text-[7px] font-semibold tracking-tight"
                >
                  {dot.end.label}
                </text>
              )}
            </g>
          );
        })}

        {origin && (
          <g>
            {(() => {
              const o = projectPoint(origin.lat, origin.lng);
              return (
                <>
                  <circle cx={o.x} cy={o.y} r="3.4" fill="#00a558" />
                  <circle cx={o.x} cy={o.y} r="3.4" fill="#00a558" opacity="0.5">
                    <animate attributeName="r" from="3" to="12" dur="2s" repeatCount="indefinite" />
                    <animate attributeName="opacity" from="0.5" to="0" dur="2s" repeatCount="indefinite" />
                  </circle>
                  <text
                    x={o.x}
                    y={o.y + 16}
                    textAnchor="middle"
                    className="fill-ink text-[8.5px] font-bold tracking-tight"
                  >
                    {origin.label}
                  </text>
                </>
              );
            })()}
          </g>
        )}
      </svg>
    </div>
  );
}
